name: Deploy

on:
  pull_request:
    branches: [develop, main]
  workflow_dispatch:

# for each ref (branch/pr) run just the most recent, cancel other pending/running ones
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    env:
      test_secret: ${{ secrets.TEST_SECRET }}
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: |
        echo Hello there! $test_secret
