name: Deploy

on:
  pull_request:
    branches: [develop, main]
  pull_request_target:
    types: [labeled]
    branches: [develop, main]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    env:
      test_secret: ${{ secrets.TEST_SECRET }}
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')

    steps:
    - name: Test
      run: |
        echo Hello there! $test_secret
